name = "blog-c4605"
compatibility_date = "2025-01-01"

[observability]
enabled = true

[[routes]]
pattern = "blog.c4605.com"
custom_domain = true

[assets]
directory = "./dist"
binding = "ASSETS"
run_worker_first = [
  "/*",
  "!/assets/*",

  "!/*.js",
  "!/*.mjs",
  "!/*.ts",
  "!/*.mts",
  "!/*.tsx",
  "!/*.js.map",
  "!/@*",

  "!/*.css",
  "!/*.scss",

  "!/*.ico",
  "!/*.png",
  "!/*.svg",

  "!/robots.txt",
  "!/.well-known/*",
]
